version: '3.8'

networks:
  backend-net:
    internal: true
  public-net:
    driver: bridge

services:

  config-server:
    image: config-server:latest
    container_name: config_server_container
    restart: no
    networks:
      - backend-net
      - public-net
    expose:
      - "8888"

  eureka-server:
    image: eureka-server:latest
    container_name: eureka_server_container
    restart: no
    networks:
      - backend-net
    expose:
      - "8761"

  gateway-service:
    image: gateway-service:latest
    container_name: gateway_service_container
    restart: no
    depends_on:
      - eureka-server
    networks:
      - backend-net
      - public-net
    ports:
      - "8080:8080"   # ✅ единственный внешний порт

  organization-service:
    image: organization-service:latest
    container_name: organization_service_container
    restart: no
    depends_on:
      - eureka-server
      - config-server
      - organization-db
    networks:
      - backend-net
    expose:
      - "8081"
    environment:
      DB_URL: r2dbc:postgresql://organization-db:5432/${DB_ORG_NAME}
      DB_URL_2: jdbc:postgresql://organization-db:5432/${DB_ORG_NAME}
      DB_USER: ${DB_ORG_USER}
      DB_PASS: ${DB_ORG_PASS}

  organization-db:
    image: postgres:17
    container_name: organization_db_container
    restart: no
    networks:
      - backend-net
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_ORG_USER}
      POSTGRES_PASSWORD: ${DB_ORG_PASS}
      POSTGRES_DB: ${DB_ORG_NAME}
    volumes:
      - organization_db_data:/var/lib/postgresql/data

  user-service:
    image: user-service:latest
    container_name: user_service_container
    restart: no
    depends_on:
      - eureka-server
      - config-server
      - user-db
    networks:
      - backend-net
    expose:
      - "8082"
    environment:
      DB_URL: jdbc:postgresql://user-db:5432/${DB_USER_NAME}
      DB_USER: ${DB_USER_USER}
      DB_PASS: ${DB_USER_PASS}

  user-db:
    image: postgres:17
    container_name: user_db_container
    restart: no
    networks:
      - backend-net
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_USER_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASS}
      POSTGRES_DB: ${DB_USER_NAME}
    volumes:
      - user_db_data:/var/lib/postgresql/data

  vacancy-service:
    image: vacancy-service:latest
    container_name: vacancy_service_container
    restart: no
    depends_on:
      - eureka-server
      - config-server
      - vacancy-db
    networks:
      - backend-net
    expose:
      - "8083"
    environment:
      DB_URL: jdbc:postgresql://vacancy-db:5432/${DB_VACANCY_NAME}
      DB_USER: ${DB_VACANCY_USER}
      DB_PASS: ${DB_VACANCY_PASS}

  vacancy-db:
    image: postgres:17
    container_name: vacancy_db_container
    restart: no
    networks:
      - backend-net
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${DB_VACANCY_USER}
      POSTGRES_PASSWORD: ${DB_VACANCY_PASS}
      POSTGRES_DB: ${DB_VACANCY_NAME}
    volumes:
      - vacancy_db_data:/var/lib/postgresql/data

volumes:
  organization_db_data:
  user_db_data:
  vacancy_db_data:
