server:
  port: 8084
spring:
  application:
    name: vacancy-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #todo: update -> validate

  # flyway:
  #   enabled: true
  #   url: ${DB_URL}
  #   user: ${DB_USER}
  #   password: ${DB_PASS}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  hystrix:
    enabled: true