
server:
  port: 8081


spring:
  application:
    name: organization-service

  r2dbc:
    # url: r2dbc:postgresql://localhost:5432/vacancy
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  flyway:
    url: ${DB_URL_2}
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  hystrix:
    enabled: true