server:
  port: 8081

spring:
  r2dbc:
    # url: r2dbc:postgresql://localhost:5432/organization_db
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  flyway:
    url: ${DB_URL_2}
    locations: classpath:db/migration
    baseline-on-migrate: true

  output:
    ansi.enabled: ALWAYS
